# 36讲(21)

<a name="uGiEq"></a>
# panic函数、recover函数以及defer语句 （上）

<a name="jEKJ1"></a>
### **从 panic 被引发到程序终止运行的大致过程是什么？**
**某个函数中的某行代码有意或无意地引发了一个 panic。这时，初始的 panic 详情会被建立起来，并且该程序的控制权会立即从此行代码转移至调用其所属函数的那行代码上，也就是调用栈中的上一级。<br />这也意味着，此行代码所属函数的执行随即终止。紧接着，控制权并不会在此有片刻的停留，它又会立即转移至再上一级的调用代码处。**控制权如此一级一级地沿着调用栈的反方向传播至顶端**，也就是我们编写的最外层函数那里。<br />这里的最外层函数指的是`go`函数，对于主 goroutine 来说就是`main`函数。但是控制权也不会停留在那里，而是**被 Go 语言运行时系统收回。**<br />随后，程序崩溃并终止运行，承载程序这次运行的进程也会随之死亡并消失。与此同时，在这个控制权传播的过程中，panic 详情会被逐渐地积累和完善，并会在程序终止之前被打印出来。

例如

```go

package main

import (
	"fmt"
)

func main() {
	fmt.Println("Enter function main.")
	caller1()
	fmt.Println("Exit function main.")
}

func caller1() {
	fmt.Println("Enter function caller1.")
	caller2()
	fmt.Println("Exit function caller1.")
}

func caller2() {
	fmt.Println("Enter function caller2.")
	s1 := []int{0, 1, 2, 3, 4}
	e5 := s1[5]
	_ = e5
	fmt.Println("Exit function caller2.")
}

Enter function main.
Enter function caller1.
Enter function caller2.
panic: runtime error: index out of range

goroutine 1 [running]:
main.caller2()
	/Users/nick/go/src/awesomeProject/src/ch1/main/hello_world.go:23 +0x7b
main.caller1()
	/Users/nick/go/src/awesomeProject/src/ch1/main/hello_world.go:16 +0x7f
main.main()
	/Users/nick/go/src/awesomeProject/src/ch1/main/hello_world.go:10 +0x7f

```
![download.png](https://cdn.nlark.com/yuque/0/2019/png/433338/1571391082784-d6b31cf8-4c83-47d3-be48-ffd627a60099.png#align=left&display=inline&height=1060&name=download.png&originHeight=1060&originWidth=887&search=&size=341347&status=done&width=887)

<a name="BR8Pb"></a>
### 一个函数怎样才能把 panic 转化为`error`类型值，并将其作为函数的结果值返回给调用方
通过recover()函数，捕获panic

```go

package main

import (
	"fmt"
)

func main() {
	fmt.Println("Enter function main.")
	caller1()
	fmt.Println("Exit function main.")
}

func caller1() {
	fmt.Println("Enter function caller1.")
	caller2()
	fmt.Println("Exit function caller1.")
}

func caller2() {
    // 在引发painc 退出函数之前会进入 defer ，painc被recover捕获
	defer func() {
		if p := recover(); p != nil {
			fmt.Printf("Recovered panic:%s\n", p)
		}
	}()
	fmt.Println("Enter function caller2.")
	s1 := []int{0, 1, 2, 3, 4}
    // 访问地址超限，报panic
	e5 := s1[5]
	_ = e5
	fmt.Println("Exit function caller2.")
}

Enter function main.
Enter function caller1.
Enter function caller2.
Recovered panic:runtime error: index out of range
Exit function caller1.
Exit function main.
```
<br />
